include ../theos/makefiles/common.mk

BUNDLE_NAME = MiBandAlertSettings
MiBandAlertSettings_FILES = MiBandAlertSettingsController.mm
MiBandAlertSettings_INSTALL_PATH = /Library/PreferenceBundles
MiBandAlertSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
MiBandAlertSettings_PRIVATE_FRAMEWORKS = Preferences
MiBandAlertSettings_CFLAGS = -fobjc-arc
MiBandAlertSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include ../theos/makefiles/bundle.mk
